/*
 * DRCAdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package userinterface.DRCManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class DRCAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    UserAccount account;
    Organization organization;
    /** Creates new form AdminWorkAreaJPanel */
    public DRCAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.account = account;
        this.organization = organization;
//        valueLabel.setText(enterprise.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    

    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnAddDisability = new javax.swing.JButton();
        BtnApproveDisabilityRequest = new javax.swing.JButton();
        BtnManageDisability1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DRC Work Area -Aminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        BtnAddDisability.setText("Manage Disabilities");
        BtnAddDisability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddDisabilityActionPerformed(evt);
            }
        });
        add(BtnAddDisability, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 350, 30));

        BtnApproveDisabilityRequest.setText("Approve Disability Request");
        BtnApproveDisabilityRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnApproveDisabilityRequestActionPerformed(evt);
            }
        });
        add(BtnApproveDisabilityRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 350, 30));

        BtnManageDisability1.setText("Add Disabilities");
        BtnManageDisability1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageDisability1ActionPerformed(evt);
            }
        });
        add(BtnManageDisability1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 350, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddDisabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddDisabilityActionPerformed
        // TODO add your handling code here:
        ManageDisabilityJPanel panel = new ManageDisabilityJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("ManageDisabilityWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BtnAddDisabilityActionPerformed

    private void BtnApproveDisabilityRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnApproveDisabilityRequestActionPerformed
        // TODO add your handling code here:
        ApproveDRCRequestJPanel panel = new ApproveDRCRequestJPanel(userProcessContainer, enterprise, system, account, organization);
        userProcessContainer.add("ApproveProviderRequestJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BtnApproveDisabilityRequestActionPerformed

    private void BtnManageDisability1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageDisability1ActionPerformed
        // TODO add your handling code here:
        AddDisabilityJPanel panel = new AddDisabilityJPanel(userProcessContainer, system.getDisabilityCatalog());
        userProcessContainer.add("AddDisabilityJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BtnManageDisability1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddDisability;
    private javax.swing.JButton BtnApproveDisabilityRequest;
    private javax.swing.JButton BtnManageDisability1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
