/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DRCManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Inventory.Patient;
import Business.Network.Network;
import Business.Organization.NGOAdminOrganization;
import Business.Organization.Organization;
import Business.Organization.VolunteerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DRCWorkRequest;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Multipart;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author krapa
 */
public class ViewPatientRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientRequestJPanel
     *
     */
    private JPanel userProcessContainer;
    private DRCWorkRequest workRequest;
    private EcoSystem business;

    public ViewPatientRequestJPanel(JPanel userProcessContainer, DRCWorkRequest workRequest, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.workRequest = workRequest;
        this.business = business;
        renderView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnProcess = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcontactnumber = new javax.swing.JTextField();
        txtemergencyContact = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdesc = new javax.swing.JTextArea();
        txtdisability = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("PATIENT GENERAL REQUEST FORM");

        BtnProcess.setText("Process Request");
        BtnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProcessActionPerformed(evt);
            }
        });

        jLabel6.setText("Patient Contact Number:");

        jLabel14.setText("Patient Email:");

        jLabel15.setText("Emergency Contact:");

        jLabel3.setText("Patient Name:");

        jLabel2.setText("Disability: ");

        jLabel4.setText("Description of need:");

        txtdesc.setColumns(20);
        txtdesc.setRows(5);
        jScrollPane2.setViewportView(txtdesc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                        .addComponent(txtcontactnumber))
                                    .addComponent(txtemergencyContact)
                                    .addComponent(txtemail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtdisability)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(BtnProcess))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcontactnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtemergencyContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdisability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(BtnProcess)
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProcessActionPerformed
        Organization org = null;
        for (Network networkObj : business.getNetworkList()) {
            for (Enterprise enterpriseObj : networkObj.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterpriseObj instanceof NGOEnterprise) {
                    for (Organization orgObj : enterpriseObj.getOrganizationDirectory().getOrganizationList()) {
                        if (orgObj instanceof VolunteerOrganization)
                            org = orgObj;
                    }
                }
            }
        }
        if(org == null) {
            JOptionPane.showMessageDialog(null, "Could not find the NGO Enterprise");
            return;
        }
        UserAccount availableVolunteer = org.getUserAccountDirectory().getFirstAvailableUser();
        if(availableVolunteer == null) {
            JOptionPane.showMessageDialog(null, "No available volunteers");
            return;
        }
        
        workRequest.setReceiver(availableVolunteer);
        availableVolunteer.setAvailability(false);
        workRequest.setStatus("Resolved");
        JOptionPane.showMessageDialog(null, "Assigned to " + availableVolunteer.toString());
        emailFunction();
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BtnProcessActionPerformed

    private void renderView() {
        Patient person = workRequest.getPerson();
        txtname.setText(person.getName());
        txtname.setEnabled(false);
        txtcontactnumber.setText(person.getPhonenumber().toString());
        txtcontactnumber.setEnabled(false);
        txtemergencyContact.setText(person.getEmergencynumber().toString());
        txtemergencyContact.setEnabled(false);
        txtemail.setText(person.getEmailId());
        txtemail.setEnabled(false);
        txtdesc.setText(person.getDescription());
        txtdesc.setEnabled(false);
        txtdisability.setText(workRequest.getDisability());
        txtdisability.setEnabled(false);
    }

    public void emailFunction() {
        Patient person = workRequest.getPerson();
        Properties prop = new Properties();
        prop.put("mail.smtp.user", "happyhandsalbatross@gmail.com");
        prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "465");

        prop.put("mail.smtp.starttls.enable", "true");
        prop.put("mail.smtp.debug", "true");

        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.socketFactory.port", "465"); //its mentioned in java site for SSL port is 465 for ssl
        prop.put("mail.smtp.socketFactory.Class", "javax.net.ssl.SSLSocketFactory");

        Session session = Session.getDefaultInstance(prop, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication("happyhandsalbatross@gmail.com", "happyhands123");
            }
        }
        );
        try {
            Message mess = new MimeMessage(session);
            mess.setFrom(new InternetAddress("happyhands795@gmail.com"));
            mess.setRecipients(Message.RecipientType.TO, InternetAddress.parse(person.getEmailId()));
            mess.setSubject("Request Process From Happy Hands");
            // mess.setText("Test mail from Ecoguard");
            //Transport.send(mess);

            //Attachment
            MimeBodyPart msgBodyPart = new MimeBodyPart();
            msgBodyPart.setText("Hi,");
            msgBodyPart.setText("Your Request has been Approved You will be shortly contacted by the volunteer.");
            Multipart multiPart = new MimeMultipart();

            // String fileAbPath = convertToPdf();
            String filepath = "G:\\MARIA\\Dinesh_CV_1march.pdf";

            MimeBodyPart msgBodyPart2 = new MimeBodyPart();
            DataSource src = new FileDataSource(filepath);
            msgBodyPart2.setDataHandler(new DataHandler(src));
            msgBodyPart2.setFileName("Ecoguard Analysis.pdf");

            multiPart.addBodyPart(msgBodyPart);

            mess.setContent(multiPart);

            Transport transport = session.getTransport("smtps");
            transport.connect("smtp.gmail.com", Integer.valueOf("465"), "happyhandsalbatross@gmail.com", "happyhands123");
            transport.sendMessage(mess, mess.getAllRecipients());
            transport.close();

            JOptionPane.showMessageDialog(null, "Request has been approved");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtcontactnumber;
    private javax.swing.JTextArea txtdesc;
    private javax.swing.JTextField txtdisability;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtemergencyContact;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
