/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Distributor;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;


import javax.swing.JPanel;

/**
 *
 * @author Preethi Jerome
 */
public class DistributorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DistributorWorkAreaJPanel
     */
    JPanel userProcessContainer;
      Organization organization;
    Enterprise enterprise;
    UserAccount userAccount;
    EcoSystem business;
    public DistributorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business = business;
        this.enterprise=enterprise;
        this.organization=organization;
        this.userAccount=userAccount;
    }

    

   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnViewShipmentOrder = new javax.swing.JButton();
        btnProcessCDCRequest = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("      Welcome to the Distributor Work Area");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 480, 53));

        btnViewShipmentOrder.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnViewShipmentOrder.setText("View Shipment Orders>>");
        btnViewShipmentOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewShipmentOrderActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewShipmentOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 400, 30));

        btnProcessCDCRequest.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnProcessCDCRequest.setText("Process Requests>>");
        btnProcessCDCRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessCDCRequestActionPerformed(evt);
            }
        });
        jPanel2.add(btnProcessCDCRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 400, 30));

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1363, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewShipmentOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewShipmentOrderActionPerformed
//        ViewShipmentOrdersJPanel panel = new ViewShipmentOrdersJPanel(userProcessContainer,organization,enterprise);
//        userProcessContainer.add("ViewShipmentOrdersJPanel",panel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnViewShipmentOrderActionPerformed

    private void btnProcessCDCRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessCDCRequestActionPerformed
        ManageDRCRequestJPanel panel = new ManageDRCRequestJPanel(userProcessContainer, organization, userAccount, business,enterprise);
        userProcessContainer.add("MaangeCDCRequestsJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProcessCDCRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcessCDCRequest;
    private javax.swing.JButton btnViewShipmentOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
